events {}
http {
    server {
        listen 80;
        
        location / {
            return 200 "Smart Task Manager API Gateway\n\nДоступные эндпоинты:\n/auth/health - Auth Service\n/tasks/health - Task Service\n";
        }
        
        location /auth/ {
            rewrite ^/auth(/.*)$ $1 break;
            proxy_pass http://auth-service:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /tasks/ {
            rewrite ^/tasks(/.*)$ $1 break;
            proxy_pass http://task-service:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}