server {
    listen 80;
    
    location / {
        return 200 "Smart Task Manager Gateway\n\nUse:\n- /auth/* for Auth\n- /tasks/* for Tasks\n";
    }
    
    location /auth/ {
        proxy_pass http://auth-service:8001/;
    }
    
    location /tasks/ {
        proxy_pass http://task-service:8002/;
    }
}
